[WIP] Started working through the and refining the failing Makefile rules.

diff --git a/build/GNUmakefile b/build/GNUmakefile
--- a/build/GNUmakefile
+++ b/build/GNUmakefile
@@ -13,6 +13,9 @@ OBJ_EXT := v
 OBJ_VVP_EXT := vvp
 OBJ_SBY_EXT := sby
 
+ARGS_EXT := args
+MAX_ARGS := 16
+
 TB_EXT := tb
 H_SRC_EXT := h.$(SRC_EXT)
 IF_SRC_EXT := if.$(SRC_EXT)
@@ -31,9 +34,6 @@ IVERILOG_DEPS_EXT := ideps
 FILE_DEPS_EXT := fdeps
 MAKE_DEPS_EXT := mdeps
 SV2V_DEPS_EXT := sdeps
-ARGS_EXT := args
-
-MAX_ARGS := 16
 
 TB_MODULE_SUFFIX := Testbench
 FV_MODULE_SUFFIX := Verification
@@ -57,18 +57,16 @@ SV2V_TB_FLAGS := $(SV2V_ALL_FLAGS)
 find_src = $(call find_files,$(SRC_DIR),$(1))
 find_files = $(shell find '$(1)' -type f -name '$(2)' 2>$(NULL_FD))
 src_to_obj = $(patsubst $(SRC_DIR)/%,$(OUT_OBJ_DIR)/%,$(1:%.$(2)=%.$(3)))
-obj_to_testbench_args = $(patsubst $(OUT_OBJ_DIR)/%,$(OUT_TESTBENCHES_DIR)/%,$(1:%.$(TB_OBJ_EXT)=%/testbench.$(MAKE_DEPS_EXT)))
-obj_to_verification_args = $(patsubst $(OUT_OBJ_DIR)/%,$(OUT_VERIFICATION_DIR)/%,$(1:%.$(OBJ_SBY_EXT)=%/verification.$(MAKE_DEPS_EXT)))
+src_to_testbench_logs = $(patsubst $(SRC_DIR)/%,$(OUT_TESTBENCHES_DIR)/%,$(1:%.$(SRC_EXT)=%.log))
+src_to_verification_logs = $(patsubst $(SRC_DIR)/%,$(OUT_VERIFICATION_DIR)/%,$(1:%.$(SRC_EXT)=%.log))
 doc_to_obj = $(patsubst $(SRC_DIR)/%,$(DOC_OBJ_DIR)/%,$(1:%.$(2)=%.$(3)))
 
 TB_SRC := $(call find_src,*.$(TB_SRC_EXT))
-TB_OBJ := $(call src_to_obj,$(TB_SRC),$(TB_SRC_EXT),$(TB_OBJ_EXT))
-TB_RUNS := $(call obj_to_testbench_args,$(TB_OBJ))
+TB_LOGS := $(call src_to_testbench_logs,$(TB_SRC))
 
 FV_SRC := $(call find_src,*.$(FV_SRC_EXT))
-FV_OBJ := $(call src_to_obj,$(FV_SRC),$(SRC_EXT),$(OBJ_EXT))
 FV_SBY_OBJ := $(call src_to_obj,$(FV_SRC),$(FV_SRC_EXT),$(OBJ_SBY_EXT))
-FV_RUNS := $(call obj_to_verification_args,$(FV_SBY_OBJ))
+FV_LOGS := $(call src_to_verification_logs,$(FV_SRC))
 
 TOP_SRC := $(call find_src,*.$(TOP_SRC_EXT))
 TOP_OBJ := $(call src_to_obj,$(TOP_SRC),$(SRC_EXT),$(OBJ_EXT))
@@ -98,9 +96,9 @@ help:
 
 all: testbenches proofs synth pnr bits docs
 
-testbenches: | $(TB_RUNS)
+testbenches: $(TB_LOGS)
 
-proofs: | $(FV_RUNS)
+proofs: $(FV_LOGS)
 
 synth: $(TOP_OBJ)
 	@echo '[SYNTH   ] TODO: RUN SYNTHESIS FOR $<';
@@ -118,9 +116,9 @@ clean:
 	@echo '[CLEAN   ] Cleaning up';
 	rm -rf '$(OUT_DIR)';
 
-prefixed_src_dirs = $(call prefixed_parent_dirs_from,$(1),$<)
-prefixed_src_dirs_from = $(call prefixed_parent_dirs,$(1),$(SRC_DIR),$2)
-prefixed_parent_dirs = $(shell next_dir(){ d=$$(dirname $$1) && echo -n "$(1)$${d} "; [ "_$${d}" != '_$(2)' ] && next_dir "$${d}"; } && next_dir '$(3)')
+prefixed_src_dirs_from_src = $(call prefixed_src_dirs_from,$(1),$<)
+prefixed_src_dirs_from = $(call prefixed_parent_dirs,$(1),$(SRC_DIR),$(2))
+prefixed_parent_dirs = $(shell next_dir(){ d=$$(dirname $$1) && echo -n "$(1)$${d} "; [ "$$?" -eq 0 -a "_$${d}" != '_$(2)' -a "_$${d}" != "_." -a "_$${d}" != "_/" ] && next_dir "$${d}"; } && [ ! -z '$(3)' ] && next_dir '$(3)')
 top_module_name_from_src = $(call top_module_name_from,$<)
 top_module_name_from = $(basename $(notdir $(patsubst %.$(TOP_SRC_EXT),%$(TOP_MODULE_SUFFIX),$(patsubst %.$(FV_SRC_EXT),%$(FV_MODULE_SUFFIX),$(1:%.$(TB_SRC_EXT)=%$(TB_MODULE_SUFFIX))))))
 top_module_name_from_make_deps = $(call top_module_name_from,$(<:%.$(MAKE_DEPS_EXT)=%.$(SRC_EXT)))
@@ -228,14 +226,12 @@ $(OUT_DOC_DIR)/%.$(DOC_WAVEDROM_OBJ_EXT).svg: $(SRC_DIR)/%.$(DOC_WAVEDROM_SRC_EX
 
 all_possible_args := $(shell seq $(MAX_ARGS))
 
-SED_REGEX_EXTRACT_DEFINES := "s/.*?(-D[^ =]+(=([^\"' ]+)|('[^']+')|(\"[^\"]+\"))?).*?/ \1/g"
-
 define DEFINE_PARAMETERISED_TOP_RECIPES
-$(OUT_TESTBENCHES_DIR)/%.$(i).$(IVERILOG_DEPS_EXT): $(OUT_TESTBENCHES_DIR)/%.$(i).$(ARGS_EXT) $(SRC_DIR)/%.$(SRC_EXT)
+$(OUT_TESTBENCHES_DIR)/%.$(i).$(IVERILOG_DEPS_EXT): $(SRC_DIR)/%.$(SRC_EXT) $(OUT_TESTBENCHES_DIR)/%.$(i).$(ARGS_EXT)
 	@set -e; \
-	echo '[DEPENDS ] $(call top_module_name_from,$(lastword $<)) ($< -> $@)'; \
-	mkdir -p '$(dir $@)'; \
-	$(IVERILOG) $(IVERILOG_DEPS_FLAGS) $(call prefixed_src_dirs_from,-I,$(lastword $<)) $(call prefixed_src_dirs_from,-y,$(lastword $<)) $$(cat '$(firstword $<)') -o '$(NULL_FD)' '-Mprefix=$@' -s '$(call top_module_name_from,$(lastword $<))' '$(lastword $<)';
+	echo '[DEPENDS ] $$(call top_module_name_from_src) ($$(lastword $$^) -> $$@)'; \
+	mkdir -p '$$(dir $$@)'; \
+	$$(IVERILOG) $$(IVERILOG_DEPS_FLAGS) $$(call prefixed_src_dirs_from_src,-I) $$(call prefixed_src_dirs_from_src,-y) $$$$(cat '$$(lastword $$^)') -o '$(NULL_FD)' '-Mprefix=$$@' -s '$$(call top_module_name_from_src)' '$$<';
 
 # TODO: OUT_VERIFICATION_DIR and OUT_TOPMODULES_DIR
 endef
@@ -244,19 +240,24 @@ $(foreach i,$(all_possible_args), \
     $(eval $(DEFINE_PARAMETERISED_TOP_RECIPES)) \
 )
 
-.PRECIOUS: %.$(IVERILOG_DEPS_EXT) %.$(FILE_DEPS_EXT) %.$(MAKE_DEPS_EXT) %.$(SV2V_DEPS_EXT)
--include $(MAKE_DEPS)
+.PHONY: %.$(IVERILOG_DEPS_EXT)
+%.$(IVERILOG_DEPS_EXT):
+	@echo '*** No recipe to make $@; do you need to increase MAX_ARGS from $(MAX_ARGS) ?';
+	@exit 1;
 
+.PRECIOUS: %.$(MAKE_DEPS_EXT)
 %.$(MAKE_DEPS_EXT): %.$(FILE_DEPS_EXT)
 	@set -e; \
 	echo '[DEPENDS ] $(call top_module_name_from_src) ($< -> $@)'; \
 	echo "$(@:%.$(DEPS_EXT)=%.$(OBJ_EXT)) $@ : $$(cat '$<')" > '$@';
 
+.PRECIOUS: %.$(FILE_DEPS_EXT)
 %.$(FILE_DEPS_EXT): %.$(IVERILOG_DEPS_EXT)
 	@set -e; \
 	echo '[DEPENDS ] $(call top_module_name_from_src) ($< -> $@)'; \
 	cat '$<' | sed -E 's/^[IM] (.+)$$/\1/' | sort | uniq | paste -sd' ' - > '$@';
 
+.PRECIOUS: %.$(SV2V_DEPS_EXT)
 %.$(SV2V_DEPS_EXT): %.$(FILE_DEPS_EXT)
 	@set -e; \
 	echo '[DEPENDS ] $(call top_module_name_from_src) ($< -> $@)'; \
@@ -264,11 +265,12 @@ $(foreach i,$(all_possible_args), \
 
 %.$(OBJ_EXT): %.$(ARGS_EXT) %.$(SV2V_DEPS_EXT)
 	@set -e; \
-	echo '[SV2V    ] $(call top_module_name_from,$(lastword $<)) ($< -> $@)'; \
+	echo '[SV2V    ] $(call top_module_name_from_src) ($< -> $@)'; \
+	only_defines="$$(cat '$<' | sed -E "s/(-D[^ =]+(=(([^\"' ]*)|('[^']*')|(\"[^\"]*\")))?)/\n\1\n/g" | grep '^-D' | paste -sd' ' -)"; \
 	$(SV2V) $(SV2V_ALL_FLAGS) \
-		$$(cat '$(firstword $<)' | sed -E '$(SED_REGEX_EXTRACT_DEFINES)') \
-		--top '$(call top_module_name_from,$(lastword $<))' \
-		$$(cat '$(lastword $<)') > $@;
+		$${only_defines} \
+		--top '$(call top_module_name_from_src)' \
+		$$(cat '$(lastword $^)') > $@;
 
 
 
@@ -277,23 +279,32 @@ $(foreach i,$(all_possible_args), \
 
 # thrash out the call hierarchy that the testbenches recipe needs; build X.log from X.*.deps (run vvp for each), build X.N.deps from each line in X.args (iverilog -Mprefix), build X.N.vvp from X.N.v, build X.N.v from X.N.deps (sv2v)
 
-$(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).log: $(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).$(MAKE_DEPS_EXT) $(wildcard $(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).*.log)
+.PRECIOUS: $(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).log
+$(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).log: $(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).$(MAKE_DEPS_EXT) out/testbenches/InstructionDecoder.tb.1.log out/testbenches/InstructionDecoder.tb.2.log
+	@echo "ALL INPUTS: $^";
 	@set -e; \
 	mkdir -p '$(dir $@)'; \
-	cat $($(filter %.log,$<):%='%') > '$@'; \
-	# TODO: grep for ^\[TB FAIL ] in $@ and abort Makefile if found
+	(cat '$(@:%.log=%.*.log)' > '$@') || echo "TODO: TEMPORARY IGNORE ERROR"; \
+	grep '\[TB FAIL \]' '$@' || echo '[TB PASS ] $(call top_module_name_from_src)';
 
-$(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).$(MAKE_DEPS_EXT): $(wildcard $(SRC_DIR)/%.$(TB_EXT).$(ARGS_EXT))
+.PRECIOUS: $(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).$(MAKE_DEPS_EXT) $(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).$(ARGS_EXT)
+$(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).$(MAKE_DEPS_EXT): $(SRC_DIR)/%.$(TB_EXT).$(ARGS_EXT) $(SRC_DIR)/%.$(TB_SRC_EXT)
 	@set -e; \
-	if [ -f '$<' ]; then \
-		mkdir -p '$(dir $@)'; \
-		seq $$(wc -l < '$<') | xargs -I ^ '$(BASH)' -c "head -n ^ '$<' | tail -n 1 > '$(@:%.$(ARGS_EXT)=%.^.$(ARGS_EXT))'"; \
-		seq $$(wc -l < '$<') | xargs -I ^ echo "$@ : $(@:%.$(TB_EXT).$(ARGS_EXT)=%.$(TB_EXT).^.log)" > '$@'; \
-	else \
-		echo "TODO: NEED TO WRITE SOMETHING TO HANDLE WHEN THERE IS NO .tb.args" && exit 1; \
-	fi
+	echo "[DEPENDS ] Creating Testbench Makefile Dependencies and Arguments ($< -> $@)"; \
+	mkdir -p '$(dir $@)'; \
+	seq $$(wc -l < $<) | xargs -I ^ '$(BASH)' -c "head -n ^ '$<' | tail -n 1 > '$(@:%.$(MAKE_DEPS_EXT)=%.^.$(ARGS_EXT))'"; \
+	seq $$(wc -l < $<) | xargs -I ^ echo "$(@:%.$(MAKE_DEPS_EXT)=%.log) : $(@:%.$(MAKE_DEPS_EXT)=%.^.log)" > '$@'; \
+	seq $$(wc -l < $<) | xargs -I ^ echo "$(@:%.$(MAKE_DEPS_EXT)=%.^.$(ARGS_EXT)) : $@" >> '$@';
 
--include $(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).$(MAKE_DEPS_EXT)
+$(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).$(MAKE_DEPS_EXT): $(SRC_DIR)/%.$(TB_SRC_EXT)
+	@set -e; \
+	echo "[DEPENDS ] Creating Testbench Makefile Dependencies and Arguments ($< -> $@)"; \
+	mkdir -p '$(dir $@)'; \
+	echo "" > '$(@:%.$(MAKE_DEPS_EXT)=%.1.$(ARGS_EXT))'; \
+	echo "$(@:%.$(MAKE_DEPS_EXT)=%.log) : $(@:%.$(MAKE_DEPS_EXT)=%.1.log)" > '$@'; \
+	echo "$(@:%.$(MAKE_DEPS_EXT)=%.1.$(ARGS_EXT)) : $@" >> '$@';
+
+#-include $(OUT_TESTBENCHES_DIR)/%.$(TB_EXT).$(MAKE_DEPS_EXT)
 
 $(OUT_TESTBENCHES_DIR)/%.log : $(OUT_TESTBENCHES_DIR)/%.$(OBJ_VVP_EXT)
 	# TODO: top_module_name_from_src is not what we want here...
@@ -302,4 +313,7 @@ $(OUT_TESTBENCHES_DIR)/%.log : $(OUT_TESTBENCHES_DIR)/%.$(OBJ_VVP_EXT)
 	($(VVP) $(VVP_TB_FLAGS) '$<' 2>&1 | tee '$@') || echo "[TB FAIL ] Exit code $?, see $@ for details";
 
 %.$(OBJ_VVP_EXT) : %.$(OBJ_EXT) %.$(ARGS_EXT)
-	echo "TODO: run iverilog here, using '$(firstword $<)' for source and '$(lastword $<)' for arguments, with -o '$@'";
+	echo "TODO: run iverilog here, using '$<' for source and '$(lastword $^)' for arguments, with -o '$@'";
+	touch '$@'
+
+-include out/testbenches/InstructionDecoder.tb.mdeps # $(call find_files,$(OUT_OBJ_DIR),*.$(MAKE_DEPS_EXT))
